//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.04.30 at 04:47:20 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.i2b2.org/xsd/hive/pdo/1.1/")
package edu.harvard.i2b2.common.datavo.pdo;
