package edu.harvard.i2b2.crc.datavo.db;
// Generated Oct 10, 2006 5:52:18 PM by Hibernate Tools 3.1.0.beta5



/**
 * QtXmlResult generated by hbm2java
 */
public class QtXmlResult  implements java.io.Serializable {

    // Fields    

     private Integer xmlResultId;
     private QtQueryResultInstance qtQueryResultInstance;
     private String xmlValue;

     // Constructors

    /** default constructor */
    public QtXmlResult() {
    }

	/** minimal constructor */
    public QtXmlResult(Integer xmlResultId) {
        this.xmlResultId = xmlResultId;
    }
    /** full constructor */
    public QtXmlResult(Integer xmlResultId, QtQueryResultInstance qtQueryResultInstance, String xmlValue) {
       this.xmlResultId = xmlResultId;
       this.qtQueryResultInstance = qtQueryResultInstance;
       this.xmlValue = xmlValue;
    }
    
   
    // Property accessors
    public Integer getXmlResultId() {
        return this.xmlResultId;
    }
    
    public void setXmlResultId(Integer xmlResultId) {
        this.xmlResultId = xmlResultId;
    }
    public QtQueryResultInstance getQtQueryResultInstance() {
        return this.qtQueryResultInstance;
    }
    
    public void setQtQueryResultInstance(QtQueryResultInstance qtQueryResultInstance) {
        this.qtQueryResultInstance = qtQueryResultInstance;
    }
    public String getXmlValue() {
        return this.xmlValue;
    }
    
    public void setXmlValue(String xmlValue) {
        this.xmlValue = xmlValue;
    }




}


