//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.04.30 at 04:47:23 PM EDT 
//


package edu.harvard.i2b2.crc.loader.datavo.loader.query;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.harvard.i2b2.crc.loader.datavo.loader.query package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _LoadDataResponse_QNAME = new QName("http://www.i2b2.org/xsd/cell/crc/loader/1.1/", "load_data_response");
    private final static QName _GetUploadInfoRequest_QNAME = new QName("http://www.i2b2.org/xsd/cell/crc/loader/1.1/", "get_upload_info_request");
    private final static QName _LoadDataListResponse_QNAME = new QName("http://www.i2b2.org/xsd/cell/crc/loader/1.1/", "load_data_list_response");
    private final static QName _PublishDataRequest_QNAME = new QName("http://www.i2b2.org/xsd/cell/crc/loader/1.1/", "publish_data_request");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.harvard.i2b2.crc.loader.datavo.loader.query
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LoadDataResponseType }
     * 
     */
    public LoadDataResponseType createLoadDataResponseType() {
        return new LoadDataResponseType();
    }

    /**
     * Create an instance of {@link OutputOptionType }
     * 
     */
    public OutputOptionType createOutputOptionType() {
        return new OutputOptionType();
    }

    /**
     * Create an instance of {@link StatusType }
     * 
     */
    public StatusType createStatusType() {
        return new StatusType();
    }

    /**
     * Create an instance of {@link InputOptionListType }
     * 
     */
    public InputOptionListType createInputOptionListType() {
        return new InputOptionListType();
    }

    /**
     * Create an instance of {@link FactOutputOptionType }
     * 
     */
    public FactOutputOptionType createFactOutputOptionType() {
        return new FactOutputOptionType();
    }

    /**
     * Create an instance of {@link OutputOptionListType }
     * 
     */
    public OutputOptionListType createOutputOptionListType() {
        return new OutputOptionListType();
    }

    /**
     * Create an instance of {@link StatusType.Condition }
     * 
     */
    public StatusType.Condition createStatusTypeCondition() {
        return new StatusType.Condition();
    }

    /**
     * Create an instance of {@link DataListType }
     * 
     */
    public DataListType createDataListType() {
        return new DataListType();
    }

    /**
     * Create an instance of {@link SetStatusType.InsertedPatientDataFileUri }
     * 
     */
    public SetStatusType.InsertedPatientDataFileUri createSetStatusTypeInsertedPatientDataFileUri() {
        return new SetStatusType.InsertedPatientDataFileUri();
    }

    /**
     * Create an instance of {@link LoadDataResponseType.DataFileLocationUri }
     * 
     */
    public LoadDataResponseType.DataFileLocationUri createLoadDataResponseTypeDataFileLocationUri() {
        return new LoadDataResponseType.DataFileLocationUri();
    }

    /**
     * Create an instance of {@link SetStatusType }
     * 
     */
    public SetStatusType createSetStatusType() {
        return new SetStatusType();
    }

    /**
     * Create an instance of {@link LoadOptionType }
     * 
     */
    public LoadOptionType createLoadOptionType() {
        return new LoadOptionType();
    }

    /**
     * Create an instance of {@link LoadDataListResponseType }
     * 
     */
    public LoadDataListResponseType createLoadDataListResponseType() {
        return new LoadDataListResponseType();
    }

    /**
     * Create an instance of {@link SetStatusType.IgnoredPatientDataFileUri }
     * 
     */
    public SetStatusType.IgnoredPatientDataFileUri createSetStatusTypeIgnoredPatientDataFileUri() {
        return new SetStatusType.IgnoredPatientDataFileUri();
    }

    /**
     * Create an instance of {@link GetUploadInfoRequestType }
     * 
     */
    public GetUploadInfoRequestType createGetUploadInfoRequestType() {
        return new GetUploadInfoRequestType();
    }

    /**
     * Create an instance of {@link FactLoadOptionType }
     * 
     */
    public FactLoadOptionType createFactLoadOptionType() {
        return new FactLoadOptionType();
    }

    /**
     * Create an instance of {@link LoadType }
     * 
     */
    public LoadType createLoadType() {
        return new LoadType();
    }

    /**
     * Create an instance of {@link Examples.MessageBody }
     * 
     */
    public Examples.MessageBody createExamplesMessageBody() {
        return new Examples.MessageBody();
    }

    /**
     * Create an instance of {@link Examples }
     * 
     */
    public Examples createExamples() {
        return new Examples();
    }

    /**
     * Create an instance of {@link PublishDataRequestType }
     * 
     */
    public PublishDataRequestType createPublishDataRequestType() {
        return new PublishDataRequestType();
    }

    /**
     * Create an instance of {@link DataListType.LocationUri }
     * 
     */
    public DataListType.LocationUri createDataListTypeLocationUri() {
        return new DataListType.LocationUri();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoadDataResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.i2b2.org/xsd/cell/crc/loader/1.1/", name = "load_data_response")
    public JAXBElement<LoadDataResponseType> createLoadDataResponse(LoadDataResponseType value) {
        return new JAXBElement<LoadDataResponseType>(_LoadDataResponse_QNAME, LoadDataResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetUploadInfoRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.i2b2.org/xsd/cell/crc/loader/1.1/", name = "get_upload_info_request")
    public JAXBElement<GetUploadInfoRequestType> createGetUploadInfoRequest(GetUploadInfoRequestType value) {
        return new JAXBElement<GetUploadInfoRequestType>(_GetUploadInfoRequest_QNAME, GetUploadInfoRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoadDataListResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.i2b2.org/xsd/cell/crc/loader/1.1/", name = "load_data_list_response")
    public JAXBElement<LoadDataListResponseType> createLoadDataListResponse(LoadDataListResponseType value) {
        return new JAXBElement<LoadDataListResponseType>(_LoadDataListResponse_QNAME, LoadDataListResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PublishDataRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.i2b2.org/xsd/cell/crc/loader/1.1/", name = "publish_data_request")
    public JAXBElement<PublishDataRequestType> createPublishDataRequest(PublishDataRequestType value) {
        return new JAXBElement<PublishDataRequestType>(_PublishDataRequest_QNAME, PublishDataRequestType.class, null, value);
    }

}
